- name: Disable mist.io collectd
  hosts: "{{ hosts | default('all') }}"
  gather_facts: no
  sudo: yes
  tasks:
    - name: Stop collectd
      shell: /opt/mistio-collectd/collectd.sh stop
      ignore_errors: yes

    - name: Remove /etc/cron.d/mistio-collectd
      file:
        path: /etc/cron.d/mistio-collectd
        state: absent
      register: cron_d

    - name: Remove mistio entries from /etc/crontab if /etc/cron.d/mistio-collectd not found
      replace:
        dest: /etc/crontab
        regexp: "^.*mistio.*$"
      register: crontab
      when: not cron_d.changed

    - name: Remove entry from /etc/rc.local if none found in /etc/crontab or /etc/cron.d/mistio-collectd
      replace:
        dest: /etc/rc.local
        regexp: "^.*mistio.*$"
      register: rc_local
      when: not cron_d.changed and not crontab.changed

    - name: Fail if no cronjobs or init commands could be found in order to be removed
      fail:
        msg: /etc/cron.d/mistio-collectd missing and no relevant entries found in either /etc/crontab or /etc/rc.local
      when: not cron_d.changed and not crontab.changed and not rc_local.changed
