- name: Get to know the servers a bit
  hosts: "{{ hosts | default('all') }}"
  tasks:
    - name: Discover OS
      debug:
        msg: "{{ ansible_distribution }}"
    - name: Discover OS family
      debug:
        msg: "{{ ansible_os_family }}"
    - name: Discover package manager
      debug:
        msg: "{{ ansible_pkg_mgr }}"
    - name: Group servers per OS family
      group_by: key={{ ansible_os_family }}


- name: Install CollectD for Debian based distros (tested only with ubuntu)
  hosts: Debian
  gather_facts: no
  sudo: yes
  tasks:
    - name: Update package list
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Check if /etc/init.d/collectd exists
      stat: path=/etc/init.d/collectd
      register: st
    - name: Install collectd
      apt:
        pkg: collectd
        state: present
      ignore_errors: yes
    - name: Disable collectd as a system service, if it wasn't previously running
      service:
        name: collectd
        state: stopped
        enabled: no
      when: not st.stat.exists  # => collectd wasn't previously installed (fixes issue with apt)


- name: Install CollectD for RedHat based distros (tested only with AMI)
  hosts: RedHat
  gather_facts: no
  sudo: yes
  tasks:
    - name: Install collectd
      yum:
        name: collectd
        state: present


- name: Install CollectD for FreeBSD
  hosts: FreeBSD
  gather_facts: no
  sudo: yes
  tasks:
    - name: FreeBSD support not yet implemented
      debug: msg=sorry


- name: Set up mistio-collectd cron entries (if applicable)
  hosts: Debian:RedHat
  gather_facts: no
  sudo: yes
  tasks:
    - name: Set up cron entry for mistio-collectd to start at boot
      cron:
        name: mistio-collectd
        user: root
        special_time: reboot
        job: /opt/mistio-collectd/collectd.sh start
        cron_file: mistio-collectd
    - name: Set up cron entry to restart mistio-collectd daily
      cron:
        name: mistio-collectd daily restart to resolve monitor hostname
        user: root
        minute: 0
        hour: 0
        job: /opt/mistio-collectd/collectd.sh restart
        cron_file: mistio-collectd


- name: Write config files and start collectd
  hosts: "{{ hosts | default('all') }}"
  gather_facts: no
  sudo: yes
  vars:
    uuid: uuid
    monitor: monitor1.mist.io
    password: 12345678
  tasks:
    - name: Create /opt/mistio-collectd/ directory
      file:
        path: /opt/mistio-collectd
        state: directory
    - name: Generate collectd config file
      template:
        src: collectd.conf.j2
        dest: /opt/mistio-collectd/collectd.conf
    - name: Generate collectd init script
      copy:
        src: collectd.sh
        dest: /opt/mistio-collectd/collectd.sh
        mode: 0755
    - name: Generate mistio-collectd uuid file
      copy:
        content: "{{ uuid }}"
        dest: /opt/mistio-collectd/uuid
    - name: Start collectd
      shell: /opt/mistio-collectd/collectd.sh start
