- name: Get to know the servers a bit and make sure some basic things are in order
  hosts: "{{ hosts | default('all') }}"
  tasks:

    - name: Discover OS
      debug:
        msg: "Distro: {{ ansible_distribution }}. Family: {{ ansible_os_family }}. PkgMgr: {{ ansible_pkg_mgr }}"

    - name: Check if /etc/cron.d/ exists
      stat: path=/etc/cron.d
      register: cron_d
    - name: Machine has /etc/cron.d
      set_fact:
        has_cron_d: yes
      when: cron_d.stat.exists
    - name: Machine doesn't have /etc/cron.d
      set_fact:
        has_cron_d: no
      when: not cron_d.stat.exists

    - name: Make sure /etc/resolv.conf has at least one nameserver
      command: grep ^nameserver /etc/resolv.conf
      register: grep_nameserver
      changed_when: False
      failed_when: False
    - name: "WARNING: No nameserver configured, adding 8.8.8.8 to /etc/resolv.conf"
      sudo: yes
      lineinfile:
        line: nameserver 8.8.8.8
        dest: /etc/resolv.conf
        insertafter: EOF
        state: present
      when: grep_nameserver.rc == 1

    - name: Make sure hostname is registered in /etc/hosts
      command: grep -w {{ ansible_hostname }} /etc/hosts
      register: grep_hosts
      changed_when: False
      failed_when: False
    - name: "WARNING: hostname not in /etc/hosts, adding"
      sudo: yes
      lineinfile:
        line: "127.0.0.1 {{ ansible_hostname }}"
        dest: /etc/hosts
        insertafter: EOF
        state: present
      when: grep_hosts.rc == 1

    - name: Group servers per OS family to apply OS specific steps
      group_by: key={{ ansible_os_family }}


- name: Install CollectD for Debian based distros
  hosts: Debian
  gather_facts: no
  sudo: yes
  tasks:
    - name: Update package list
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Check if /etc/init.d/collectd exists
      stat: path=/etc/init.d/collectd
      register: st
    - name: Install collectd
      apt:
        pkg: collectd
        state: present
    - name: Stop collectd system service, if it wasn't previously running
      service:
        name: collectd
        state: stopped
        # enabled: no
      when: not st.stat.exists  # => collectd wasn't previously installed
    - name: Disable collectd system service, if it wasn't previously running
      lineinfile:
        regexp: ^DISABLE=
        line: DISABLE=1
        dest: /etc/default/collectd
      when: not st.stat.exists  # => collectd wasn't previously installed


- name: Install CollectD for RedHat based distros
  hosts: RedHat
  gather_facts: no
  sudo: yes
  tasks:
    - name: Check if /etc/yum.repos.d/epel.repo exists
      stat: path=/etc/yum.repos.d/epel.repo
      register: st
    - name: Install epel-release if /etc/yum.repos.d/epel.repo missing (not for Fedora)
      yum:
        name: epel-release
        state: present
      when: not st.stat.exists and ansible_distribution != 'Fedora'
    - name: Install collectd from epel repo (all except Fedora)
      yum:
        name: collectd
        state: present
        enablerepo: epel
      when: ansible_distribution != 'Fedora'
    - name: Install collectd from epel repo (only for Fedora)
      yum:
        name: collectd
        state: present
      when: ansible_distribution == 'Fedora'

- name: Install CollectD for FreeBSD
  hosts: FreeBSD
  gather_facts: no
  sudo: yes
  tasks:
    - name: FreeBSD support not yet implemented
      debug: msg=sorry


- name: Configure and start collectd
  hosts: "{{ hosts | default('all') }}"
  gather_facts: no
  sudo: yes
  vars:
    monitor: monitor1.mist.io
  tasks:

    - name: Set up cron entry for mistio-collectd to start at boot
      cron:
        name: mistio-collectd
        user: root
        special_time: reboot
        job: /opt/mistio-collectd/collectd.sh start
        cron_file: mistio-collectd
      when: has_cron_d

    - name: Set up cron entry to restart mistio-collectd daily
      cron:
        name: mistio-collectd daily restart to resolve monitor hostname
        user: root
        minute: 0
        hour: 0
        job: /opt/mistio-collectd/collectd.sh restart
        cron_file: mistio-collectd
      when: has_cron_d

    - name: /etc/cron.d missing
      debug:
        msg: seriously?
      when: not has_cron_d

    - name: Create /opt/mistio-collectd/ directory
      file:
        path: /opt/mistio-collectd
        state: directory

    - name: Generate collectd config file
      template:
        src: collectd.conf.j2
        dest: /opt/mistio-collectd/collectd.conf

    - name: Generate collectd init script
      copy:
        src: collectd.sh
        dest: /opt/mistio-collectd/collectd.sh
        mode: 0755

    - name: Generate mistio-collectd uuid file
      copy:
        content: "{{ uuid }}"
        dest: /opt/mistio-collectd/uuid

    - name: Start collectd
      shell: /opt/mistio-collectd/collectd.sh start
